arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
output-class: AppLocalizations
untranslated-messages-file: untranslated.txt
preferred-supported-locales:
  - en
  - zh
  - fr
  - de
  - ru
  - es
  - ja
  - ko
